export const ERROR_MESSAGE_NOT_FOUND = "does not found.";

export const ERROR_CODE_NOT_FOUND = "ERROR_CODE_NOT_FOUND";
export const ERROR_CODE_INCORRECT_PASSWORD = "ERROR_CODE_INCORRECT_PASSWORD";
export const ERROR_CODE_EMAIL_ALREADY_EXISTS =
  "ERROR_CODE_EMAIL_ALREADY_EXISTS";
export const ERROR_CODE_USERNAME_ALREADY_EXISTS =
  "ERROR_CODE_USERNAME_ALREADY_EXISTS";
